# -*- mode: ruby -*-
# vi: set ft=ruby ts=2 sw=2 sts=2 et :

# This Vagrantfile creates a quick OOR testbed with several VMs with OOR
# running, pre-configured for various roles (map server, mobile node, etc.)

def create_vm(config, name, rloc)
  config.vm.define name do |node|
    node.vm.hostname = name
    node.vm.network "private_network", ip: rloc
    node.vm.provision "shell", path: "config-oor.sh", args: name
    # If you prefer to run OOR manually, comment the next line
    node.vm.provision "shell", path: "run-oor.sh"
    node.vm.provider :virtualbox do |vb|
      vb.name = name
    end
  end
end

Vagrant.configure(2) do |config|
  # vagrant-cachier caches apt/yum etc. to speed subsequent `vagrant up`
  # To enable, run `vagrant plugin install vagrant-cachier`
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    config.cache.synced_folder_opts = {
      owner: '_apt',
      group: '_apt',
      mount_options: ["dmode=777", "fmode=666"]
    }
  end
  # Using Ubuntu 17.04 until Vagrant issue #9134 is fixed (Vagrant 2.0.2?)
  # https://github.com/hashicorp/vagrant/issues/9134
  config.vm.box = "ubuntu/zesty64"
  # TODO need to figure out how to use #{config.ssh.username} instead of
  # "ubuntu" to be more general, if the box we use changes the user
  username = "ubuntu"
  config.vm.synced_folder "..", "/home/#{username}/oor"
  config.vm.provision "shell", path: "install-prereqs.sh"
  config.vm.provision "shell", path: "install-optional.sh", args: username
  config.vm.provision "shell", path: "install-oor.sh", privileged: false
  config.vm.provider :virtualbox do |vb|
    vb.cpus = 1
    vb.memory = 512
    vb.linked_clone = true
    vb.customize [ "modifyvm", :id, "--description", "Open Overlay Router testbed VM" ]
    vb.customize [ "modifyvm", :id, "--nicpromisc2", "allow-all"]
    # This disables generating a log file with boot messages. If you need to
    # debug the boot process, comment the following line.
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end

  create_vm(config, "msmr", "192.168.127.2/24")
  create_vm(config, "mn1", "192.168.127.11/24")
  create_vm(config, "mn2", "192.168.127.12/24")
end
