/*
 * lispd_tun.c
 *
 * This file is part of LISP Mobile Node Implementation.
 *
 * Copyright (C) 2012 Cisco Systems, Inc, 2012. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * Please send any bug reports or fixes you make to the email address(es):
 *    LISP-MN developers <devel@lispmob.org>
 *
 * Based on code from Chris White <chris@logicalelegance.com>
 * 
 * Written or modified by:
 *    Alberto Rodriguez Natal <arnatal@ac.upc.edu>
 */

#include <errno.h>
#include <linux/netlink.h>
#include <linux/rtnetlink.h>
#include <unistd.h>

#include "../lispd_external.h"
#include "../lib/lmlog.h"
#include "../lib/routing_tables_lib.h"
#include "lispd_tun.h"


int create_tun();
int configure_routing_to_tun(uint8_t router_mode,lisp_addr_t *tun_v4_addr,
        lisp_addr_t *tun_v6_addr);
int tun_bring_up_iface();
int tun_add_eid_to_iface(lisp_addr_t *addr);
int set_tun_default_route_v4();
int set_tun_default_route_v6();

int tun_configure_data_plane(
        uint8_t router_mode,
        lisp_addr_t *ipv4_addr,
        lisp_addr_t *ipv6_addr)
{
    if (create_tun() != GOOD){
        return (BAD);
    }

    if(configure_routing_to_tun(router_mode,ipv4_addr,ipv6_addr) != GOOD) {
        return (BAD);
    }

    return (GOOD);
}

int create_tun()
{
    struct ifreq ifr;
    int err = 0;
    int tmpsocket = 0;
    int flags = IFF_TUN | IFF_NO_PI; // Create a tunnel without persistence
    char *clonedev = CLONEDEV;


    /* Arguments taken by the function:
     *
     * char *dev: the name of an interface (or '\0'). MUST have enough
     *   space to hold the interface name if '\0' is passed
     * int flags: interface flags (eg, IFF_TUN etc.)
     */

    /* open the clone device */
    if( (tun_receive_fd = open(clonedev, O_RDWR)) < 0 ) {
        LMLOG(LISP_LOG_CRIT, "TUN/TAP: Failed to open clone device");
        return(BAD);
    }

    memset(&ifr, 0, sizeof(ifr));

    ifr.ifr_flags = flags;
    strncpy(ifr.ifr_name, TUN_IFACE_NAME, IFNAMSIZ - 1);

    // try to create the device
    if ((err = ioctl(tun_receive_fd, TUNSETIFF, (void *) &ifr)) < 0) {
        close(tun_receive_fd);
        LMLOG(LISP_LOG_CRIT, "TUN/TAP: Failed to create tunnel interface, errno: %d.", errno);
        if (errno == 16){
            LMLOG(LISP_LOG_CRIT, "Check no other instance of lispd is running. Exiting ...");
        }
        return(BAD);
    }

    // get the ifindex for the tun/tap
    tmpsocket = socket(AF_INET, SOCK_DGRAM, 0); // Dummy socket for the ioctl, type/details unimportant
    if ((err = ioctl(tmpsocket, SIOCGIFINDEX, (void *)&ifr)) < 0) {
        close(tun_receive_fd);
        close(tmpsocket);
        LMLOG(LISP_LOG_CRIT, "TUN/TAP: unable to determine ifindex for tunnel interface, errno: %d.", errno);
        return(BAD);
    } else {
        LMLOG(LISP_LOG_DEBUG_3, "TUN/TAP ifindex is: %d", ifr.ifr_ifindex);
        tun_ifindex = ifr.ifr_ifindex;

        // Set the MTU to the configured MTU
        ifr.ifr_ifru.ifru_mtu = TUN_MTU;
        if ((err = ioctl(tmpsocket, SIOCSIFMTU, &ifr)) < 0) {
            close(tmpsocket);
            LMLOG(LISP_LOG_CRIT, "TUN/TAP: unable to set interface MTU to %d, errno: %d.", TUN_MTU, errno);
            return(BAD);
        } else {
            LMLOG(LISP_LOG_DEBUG_1, "TUN/TAP mtu set to %d", TUN_MTU);
        }
    }


    close(tmpsocket);

    tun_receive_buf = (uint8_t *)malloc(TUN_RECEIVE_SIZE);

    if (tun_receive_buf == NULL){
        LMLOG(LISP_LOG_WARNING, "create_tun: Unable to allocate memory for tun_receive_buf: %s", strerror(errno));
        return(BAD);
    }

    /* this is the special file descriptor that the caller will use to talk
     * with the virtual interface */
    LMLOG(LISP_LOG_DEBUG_2, "Tunnel fd at creation is %d", tun_receive_fd);

    if (tun_bring_up_iface(TUN_IFACE_NAME) != GOOD){
        return (BAD);
    }

    return(GOOD);
}

/*
* For mobile node mode, we create two /1 routes covering the full IP addresses space to route all traffic
* generated by the node to the lispTun0 interface
*          IPv4: 0.0.0.0/1 and 128.0.0.0/1
*          IPv6: ::/1      and 8000::/1
*/


int configure_routing_to_tun_mn(lisp_addr_t *eid_addr)
{

    if (tun_add_eid_to_iface(eid_addr) != GOOD){
        return (BAD);
    }

    switch (lisp_addr_ip_afi(eid_addr)){
    case AF_INET:
        if (set_tun_default_route_v4() != GOOD){
            return (BAD);
        }
        break;
    case AF_INET6:
        if (set_tun_default_route_v6() != GOOD){
            return (BAD);
        }
        break;
    default:
        return (BAD);
        break;
    }

    return (GOOD);
}


/*
* For router mode, add a new routing table with default route to tun interface. Using source routing,
* We send all traffic generated by EIDs to this table.
*/

int configure_routing_to_tun_router(int afi){


    uint32_t    iface_index     = 0;

    iface_index = if_nametoindex(TUN_IFACE_NAME);

    return add_route(afi,iface_index,NULL,NULL,NULL,RULE_TO_LISP_TABLE_PRIORITY,LISP_TABLE);

}

/*
 * Creates the routes to send the traffic to the tun interface to be encapsulated
 */
int configure_routing_to_tun(
        uint8_t router_mode,
        lisp_addr_t *tun_v4_addr,
        lisp_addr_t *tun_v6_addr)
{

    if (router_mode == FALSE)
    {
        if (tun_v4_addr != NULL){
            configure_routing_to_tun_mn(tun_v4_addr);
        }
        if (tun_v6_addr != NULL){
            configure_routing_to_tun_mn(tun_v6_addr);
        }
    }else{

        if (tun_v4_addr != NULL){
            configure_routing_to_tun_router(AF_INET);
        }
        if (tun_v6_addr != NULL){
            configure_routing_to_tun_router(AF_INET6);
        }
    }
    return (GOOD);
}



/*
 * tun_bring_up_iface()
 *
 * Bring up interface
 */
int tun_bring_up_iface()
{
    struct ifinfomsg    *ifi = NULL;
    struct nlmsghdr     *nlh = NULL;
    char                sndbuf[4096];
    int                 retval = 0;
    int                 sockfd = 0;
    int                 tun_ifindex = 0;

    tun_ifindex = if_nametoindex (TUN_IFACE_NAME);

    sockfd = socket(AF_NETLINK, SOCK_DGRAM, NETLINK_ROUTE);

    if (sockfd < 0) {
        LMLOG(LISP_LOG_ERR, "tun_add_eid_to_iface: Failed to connect to netlink socket");
        return(BAD);
    }

    /*
     * Build the command
     */
    memset(sndbuf, 0, 4096);
    nlh = (struct nlmsghdr *)sndbuf;
    nlh->nlmsg_len = NLMSG_LENGTH(sizeof(struct ifinfomsg));
    nlh->nlmsg_flags = NLM_F_REQUEST | (NLM_F_CREATE | NLM_F_REPLACE);
    nlh->nlmsg_type = RTM_SETLINK;

    ifi = (struct ifinfomsg *)(sndbuf + sizeof(struct nlmsghdr));
    ifi->ifi_family = AF_UNSPEC;
    ifi->ifi_type = IFLA_UNSPEC;
    ifi->ifi_index = tun_ifindex;
    ifi->ifi_flags = IFF_UP | IFF_RUNNING; // Bring it up
    ifi->ifi_change = 0xFFFFFFFF;

    retval = send(sockfd, sndbuf, nlh->nlmsg_len, 0);

    if (retval < 0) {
        LMLOG(LISP_LOG_ERR, "tun_bring_up_iface: send() failed %s", strerror(errno));
        close(sockfd);
        return(BAD);
    }

    LMLOG(LISP_LOG_DEBUG_1, "TUN interface UP.");
    close(sockfd);
    return(GOOD);
}

/*
 * tun_add_eid_to_iface()
 *
 * Add an EID to the TUN/TAP interface
 */
int tun_add_eid_to_iface(lisp_addr_t *addr)
{
    struct rtattr       *rta = NULL;
    struct ifaddrmsg    *ifa = NULL;
    struct nlmsghdr     *nlh = NULL;
    char                sndbuf[4096];
    int                 retval = 0;
    int                 sockfd = 0;
    int                 tun_ifindex = 0;

    int                 addr_size = 0;
    int                 prefix_length = 0;

    tun_ifindex = if_nametoindex (TUN_IFACE_NAME);

    sockfd = socket(PF_NETLINK, SOCK_DGRAM, NETLINK_ROUTE);

    if (sockfd < 0) {
        LMLOG(LISP_LOG_ERR, "tun_add_eid_to_iface: Failed to connect to netlink socket");
        return(BAD);
    }

    switch (lisp_addr_ip_afi(addr)){
    case AF_INET:
        addr_size = sizeof(struct in_addr);
        prefix_length = 32;
        break;
    case AF_INET6:
        addr_size = sizeof(struct in6_addr);
        prefix_length = 128;
        break;
    default:
        LMLOG(LISP_LOG_ERR, "tun_add_eid_to_iface: Address no IP address %s",
                lisp_addr_to_char(addr));
        return(BAD);
    }

    /*
     * Build the command
     */
    memset(sndbuf, 0, 4096);
    nlh = (struct nlmsghdr *)sndbuf;
    nlh->nlmsg_len = NLMSG_LENGTH(sizeof(struct ifaddrmsg) + sizeof(struct rtattr) + addr_size);
    nlh->nlmsg_flags = NLM_F_REQUEST | NLM_F_CREATE | NLM_F_REPLACE;
    nlh->nlmsg_type = RTM_NEWADDR;
    ifa = (struct ifaddrmsg *)(sndbuf + sizeof(struct nlmsghdr));

    ifa->ifa_prefixlen = prefix_length;
    ifa->ifa_family = lisp_addr_ip_afi(addr);
    ifa->ifa_index  = tun_ifindex;
    ifa->ifa_scope = RT_SCOPE_UNIVERSE;
    ifa->ifa_flags = 0; // Bring it up

    rta = (struct rtattr *)(sndbuf + sizeof(struct nlmsghdr) + sizeof(struct ifaddrmsg));
    rta->rta_type = IFA_LOCAL;
    rta->rta_len = sizeof(struct rtattr) + addr_size;
//    memcopy_lisp_addr((void *)((char *)rta + sizeof(struct rtattr)),&eid_address);
    lisp_addr_copy_to((void *)((char *)rta + sizeof(struct rtattr)),addr);


    retval = send(sockfd, sndbuf, nlh->nlmsg_len, 0);

    if (retval < 0) {
        LMLOG(LISP_LOG_ERR, "tun_add_eid_to_iface: send() failed %s", strerror(errno));
        close(sockfd);
        return(BAD);
    }

    LMLOG(LISP_LOG_DEBUG_1, "added %s EID to TUN interface.",lisp_addr_to_char(addr));
    close(sockfd);
    return(GOOD);
}

int set_tun_default_route_v4()
{

    /*
     * Assign route to 0.0.0.0/1 and 128.0.0.0/1 via tun interface
     */
    lisp_addr_t dest;
    lisp_addr_t *src = NULL;
    uint32_t metric = 0;

    metric = 0;

    lisp_addr_ippref_from_char("0.0.0.0/1",&dest);

    add_route(AF_INET,
            tun_ifindex,
            &dest,
            src,
            NULL,
            metric,
            RT_TABLE_MAIN);

    lisp_addr_ippref_from_char("128.0.0.0/1",&dest);

    add_route(AF_INET,
            tun_ifindex,
            &dest,
            src,
            NULL,
            metric,
            RT_TABLE_MAIN);
    return(GOOD);


}


int set_tun_default_route_v6()
{

    /*
     * Assign route to ::/1 and 8000::/1 via tun interface
     */

    lisp_addr_t dest;
    lisp_addr_t *src = NULL;
    uint32_t metric = 0;

    metric = 512;

    lisp_addr_ippref_from_char("::/1",&dest);

    add_route(AF_INET6,
            tun_ifindex,
            &dest,
            src,
            NULL,
            metric,
            RT_TABLE_MAIN);

    lisp_addr_ippref_from_char("8000::/1",&dest);

    add_route(AF_INET6,
            tun_ifindex,
            &dest,
            src,
            NULL,
            metric,
            RT_TABLE_MAIN);

    return(GOOD);
}


int del_tun_default_route_v6()
{

    /*
     * Assign route to ::/1 and 8000::/1 via tun interface
     */

    lisp_addr_t dest;
    lisp_addr_t *src    = NULL;
    lisp_addr_t *gw     = NULL;
    uint32_t metric     = 0;

    metric = 512;


    lisp_addr_ippref_from_char("::/1",&dest);

    del_route(AF_INET6,
            tun_ifindex,
            &dest,
            src,
            gw,
            metric,
            RT_TABLE_MAIN);

    lisp_addr_ippref_from_char("8000::/1",&dest);

    del_route(AF_INET6,
            tun_ifindex,
            &dest,
            src,
            gw,
            metric,
            RT_TABLE_MAIN);

    return(GOOD);
}


/*
 * Editor modelines
 *
 * vi: set shiftwidth=4 tabstop=4 expandtab:
 * :indentSize=4:tabSize=4:noTabs=true:
 */
