/*
  File autogenerated by gengetopt version 2.22.4
  generated with the following command:
  gengetopt -i lispconf.ggo 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: lispconf [OPTIONS]...";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "\n Mode: addmode",
  "  -a, --add-entry=STRING        Add a map cache or db entry  (possible \n                                  values=\"db\", \"cache\" default=`db')",
  "  -e, --eid=IP Address/Prefix Length\n                                EID in CIDR prefix notation <addr>/<len>",
  "  -r, --rloc=IP Address         RLOC as IP Address",
  "  -p, --priority=priority       priority",
  "  -w, --weight=weight           weight",
  "  -t, --ttl=Time                Time-to-live in seconds",
  "\n Mode: printmode",
  "  -x, --print=STRING            Print EID table  (possible values=\"db\", \n                                  \"cache\" default=`cache')",
  "  -f, --filter-prefix=IP Address Prefix\n                                EID prefix filter",
  "\n Mode: listmode",
  "  -l, --list=STRING             List EIDs or RLOCS  (possible values=\"eids\", \n                                  \"rlocs\" default=`eids')",
  "\n Mode: rlocmode",
  "  -i, --interface=Linux network interface device name\n                                Specify a local interface as RLOC of LISP \n                                  encapsulated packets",
    0
};

typedef enum {ARG_NO
  , ARG_STRING
  , ARG_INT
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

const char *cmdline_parser_add_entry_values[] = {"db", "cache", 0}; /*< Possible values for add-entry. */
const char *cmdline_parser_print_values[] = {"db", "cache", 0}; /*< Possible values for print. */
const char *cmdline_parser_list_values[] = {"eids", "rlocs", 0}; /*< Possible values for list. */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->add_entry_given = 0 ;
  args_info->eid_given = 0 ;
  args_info->rloc_given = 0 ;
  args_info->priority_given = 0 ;
  args_info->weight_given = 0 ;
  args_info->ttl_given = 0 ;
  args_info->print_given = 0 ;
  args_info->filter_prefix_given = 0 ;
  args_info->list_given = 0 ;
  args_info->interface_given = 0 ;
  args_info->addmode_mode_counter = 0 ;
  args_info->delmode_mode_counter = 0 ;
  args_info->listmode_mode_counter = 0 ;
  args_info->printmode_mode_counter = 0 ;
  args_info->rlocmode_mode_counter = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->add_entry_arg = gengetopt_strdup ("db");
  args_info->add_entry_orig = NULL;
  args_info->eid_arg = NULL;
  args_info->eid_orig = NULL;
  args_info->rloc_arg = NULL;
  args_info->rloc_orig = NULL;
  args_info->priority_orig = NULL;
  args_info->weight_orig = NULL;
  args_info->ttl_orig = NULL;
  args_info->print_arg = gengetopt_strdup ("cache");
  args_info->print_orig = NULL;
  args_info->filter_prefix_arg = NULL;
  args_info->filter_prefix_orig = NULL;
  args_info->list_arg = gengetopt_strdup ("eids");
  args_info->list_orig = NULL;
  args_info->interface_arg = NULL;
  args_info->interface_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->add_entry_help = gengetopt_args_info_help[3] ;
  args_info->eid_help = gengetopt_args_info_help[4] ;
  args_info->rloc_help = gengetopt_args_info_help[5] ;
  args_info->priority_help = gengetopt_args_info_help[6] ;
  args_info->weight_help = gengetopt_args_info_help[7] ;
  args_info->ttl_help = gengetopt_args_info_help[8] ;
  args_info->print_help = gengetopt_args_info_help[10] ;
  args_info->filter_prefix_help = gengetopt_args_info_help[11] ;
  args_info->list_help = gengetopt_args_info_help[13] ;
  args_info->interface_help = gengetopt_args_info_help[15] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->add_entry_arg));
  free_string_field (&(args_info->add_entry_orig));
  free_string_field (&(args_info->eid_arg));
  free_string_field (&(args_info->eid_orig));
  free_string_field (&(args_info->rloc_arg));
  free_string_field (&(args_info->rloc_orig));
  free_string_field (&(args_info->priority_orig));
  free_string_field (&(args_info->weight_orig));
  free_string_field (&(args_info->ttl_orig));
  free_string_field (&(args_info->print_arg));
  free_string_field (&(args_info->print_orig));
  free_string_field (&(args_info->filter_prefix_arg));
  free_string_field (&(args_info->filter_prefix_orig));
  free_string_field (&(args_info->list_arg));
  free_string_field (&(args_info->list_orig));
  free_string_field (&(args_info->interface_arg));
  free_string_field (&(args_info->interface_orig));
  
  

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, const char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->add_entry_given)
    write_into_file(outfile, "add-entry", args_info->add_entry_orig, cmdline_parser_add_entry_values);
  if (args_info->eid_given)
    write_into_file(outfile, "eid", args_info->eid_orig, 0);
  if (args_info->rloc_given)
    write_into_file(outfile, "rloc", args_info->rloc_orig, 0);
  if (args_info->priority_given)
    write_into_file(outfile, "priority", args_info->priority_orig, 0);
  if (args_info->weight_given)
    write_into_file(outfile, "weight", args_info->weight_orig, 0);
  if (args_info->ttl_given)
    write_into_file(outfile, "ttl", args_info->ttl_orig, 0);
  if (args_info->print_given)
    write_into_file(outfile, "print", args_info->print_orig, cmdline_parser_print_values);
  if (args_info->filter_prefix_given)
    write_into_file(outfile, "filter-prefix", args_info->filter_prefix_orig, 0);
  if (args_info->list_given)
    write_into_file(outfile, "list", args_info->list_orig, cmdline_parser_list_values);
  if (args_info->interface_given)
    write_into_file(outfile, "interface", args_info->interface_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (args_info->addmode_mode_counter && ! args_info->add_entry_given)
    {
      fprintf (stderr, "%s: '--add-entry' ('-a') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  
  if (args_info->addmode_mode_counter && ! args_info->eid_given)
    {
      fprintf (stderr, "%s: '--eid' ('-e') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  
  if (args_info->addmode_mode_counter && ! args_info->rloc_given)
    {
      fprintf (stderr, "%s: '--rloc' ('-r') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  
  if (args_info->addmode_mode_counter && ! args_info->priority_given)
    {
      fprintf (stderr, "%s: '--priority' ('-p') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  
  if (args_info->addmode_mode_counter && ! args_info->weight_given)
    {
      fprintf (stderr, "%s: '--weight' ('-w') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  
  
  /* checks for dependences among options */

  return error;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


static int check_modes(
  int given1[], const char *options1[],
                       int given2[], const char *options2[])
{
  int i = 0, j = 0, errors = 0;
  
  while (given1[i] >= 0) {
    if (given1[i]) {
      while (given2[j] >= 0) {
        if (given2[j]) {
          ++errors;
          fprintf(stderr, "%s: option %s conflicts with option %s\n",
                  package_name, options1[i], options2[j]);
        }
        ++j;
      }
    }
    ++i;
  }
  
  return errors;
}

int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "add-entry",	1, NULL, 'a' },
        { "eid",	1, NULL, 'e' },
        { "rloc",	1, NULL, 'r' },
        { "priority",	1, NULL, 'p' },
        { "weight",	1, NULL, 'w' },
        { "ttl",	1, NULL, 't' },
        { "print",	1, NULL, 'x' },
        { "filter-prefix",	1, NULL, 'f' },
        { "list",	1, NULL, 'l' },
        { "interface",	1, NULL, 'i' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVa:e:r:p:w:t:x:f:l:i:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'a':	/* Add a map cache or db entry.  */
          args_info->addmode_mode_counter += 1;
        
        
          if (update_arg( (void *)&(args_info->add_entry_arg), 
               &(args_info->add_entry_orig), &(args_info->add_entry_given),
              &(local_args_info.add_entry_given), optarg, cmdline_parser_add_entry_values, "db", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "add-entry", 'a',
              additional_error))
            goto failure;
        
          break;
        case 'e':	/* EID in CIDR prefix notation <addr>/<len>.  */
          args_info->addmode_mode_counter += 1;
        
        
          if (update_arg( (void *)&(args_info->eid_arg), 
               &(args_info->eid_orig), &(args_info->eid_given),
              &(local_args_info.eid_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "eid", 'e',
              additional_error))
            goto failure;
        
          break;
        case 'r':	/* RLOC as IP Address.  */
          args_info->addmode_mode_counter += 1;
        
        
          if (update_arg( (void *)&(args_info->rloc_arg), 
               &(args_info->rloc_orig), &(args_info->rloc_given),
              &(local_args_info.rloc_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "rloc", 'r',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* priority.  */
          args_info->addmode_mode_counter += 1;
        
        
          if (update_arg( (void *)&(args_info->priority_arg), 
               &(args_info->priority_orig), &(args_info->priority_given),
              &(local_args_info.priority_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "priority", 'p',
              additional_error))
            goto failure;
        
          break;
        case 'w':	/* weight.  */
          args_info->addmode_mode_counter += 1;
        
        
          if (update_arg( (void *)&(args_info->weight_arg), 
               &(args_info->weight_orig), &(args_info->weight_given),
              &(local_args_info.weight_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "weight", 'w',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* Time-to-live in seconds.  */
          args_info->addmode_mode_counter += 1;
        
        
          if (update_arg( (void *)&(args_info->ttl_arg), 
               &(args_info->ttl_orig), &(args_info->ttl_given),
              &(local_args_info.ttl_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "ttl", 't',
              additional_error))
            goto failure;
        
          break;
        case 'x':	/* Print EID table.  */
          args_info->printmode_mode_counter += 1;
        
        
          if (update_arg( (void *)&(args_info->print_arg), 
               &(args_info->print_orig), &(args_info->print_given),
              &(local_args_info.print_given), optarg, cmdline_parser_print_values, "cache", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "print", 'x',
              additional_error))
            goto failure;
        
          break;
        case 'f':	/* EID prefix filter.  */
          args_info->printmode_mode_counter += 1;
        
        
          if (update_arg( (void *)&(args_info->filter_prefix_arg), 
               &(args_info->filter_prefix_orig), &(args_info->filter_prefix_given),
              &(local_args_info.filter_prefix_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "filter-prefix", 'f',
              additional_error))
            goto failure;
        
          break;
        case 'l':	/* List EIDs or RLOCS.  */
          args_info->listmode_mode_counter += 1;
        
        
          if (update_arg( (void *)&(args_info->list_arg), 
               &(args_info->list_orig), &(args_info->list_given),
              &(local_args_info.list_given), optarg, cmdline_parser_list_values, "eids", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "list", 'l',
              additional_error))
            goto failure;
        
          break;
        case 'i':	/* Specify a local interface as RLOC of LISP encapsulated packets.  */
          args_info->rlocmode_mode_counter += 1;
        
        
          if (update_arg( (void *)&(args_info->interface_arg), 
               &(args_info->interface_orig), &(args_info->interface_given),
              &(local_args_info.interface_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "interface", 'i',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (args_info->addmode_mode_counter && args_info->listmode_mode_counter) {
    int addmode_given[] = {args_info->add_entry_given, args_info->eid_given, args_info->rloc_given, args_info->priority_given, args_info->weight_given, args_info->ttl_given,  -1};
    const char *addmode_desc[] = {"--add-entry", "--eid", "--rloc", "--priority", "--weight", "--ttl",  0};
    int listmode_given[] = {args_info->list_given,  -1};
    const char *listmode_desc[] = {"--list",  0};
    error += check_modes(addmode_given, addmode_desc, listmode_given, listmode_desc);
  }
  if (args_info->addmode_mode_counter && args_info->printmode_mode_counter) {
    int addmode_given[] = {args_info->add_entry_given, args_info->eid_given, args_info->rloc_given, args_info->priority_given, args_info->weight_given, args_info->ttl_given,  -1};
    const char *addmode_desc[] = {"--add-entry", "--eid", "--rloc", "--priority", "--weight", "--ttl",  0};
    int printmode_given[] = {args_info->print_given, args_info->filter_prefix_given,  -1};
    const char *printmode_desc[] = {"--print", "--filter-prefix",  0};
    error += check_modes(addmode_given, addmode_desc, printmode_given, printmode_desc);
  }
  if (args_info->addmode_mode_counter && args_info->rlocmode_mode_counter) {
    int addmode_given[] = {args_info->add_entry_given, args_info->eid_given, args_info->rloc_given, args_info->priority_given, args_info->weight_given, args_info->ttl_given,  -1};
    const char *addmode_desc[] = {"--add-entry", "--eid", "--rloc", "--priority", "--weight", "--ttl",  0};
    int rlocmode_given[] = {args_info->interface_given,  -1};
    const char *rlocmode_desc[] = {"--interface",  0};
    error += check_modes(addmode_given, addmode_desc, rlocmode_given, rlocmode_desc);
  }
  if (args_info->listmode_mode_counter && args_info->printmode_mode_counter) {
    int listmode_given[] = {args_info->list_given,  -1};
    const char *listmode_desc[] = {"--list",  0};
    int printmode_given[] = {args_info->print_given, args_info->filter_prefix_given,  -1};
    const char *printmode_desc[] = {"--print", "--filter-prefix",  0};
    error += check_modes(listmode_given, listmode_desc, printmode_given, printmode_desc);
  }
  if (args_info->listmode_mode_counter && args_info->rlocmode_mode_counter) {
    int listmode_given[] = {args_info->list_given,  -1};
    const char *listmode_desc[] = {"--list",  0};
    int rlocmode_given[] = {args_info->interface_given,  -1};
    const char *rlocmode_desc[] = {"--interface",  0};
    error += check_modes(listmode_given, listmode_desc, rlocmode_given, rlocmode_desc);
  }
  if (args_info->printmode_mode_counter && args_info->rlocmode_mode_counter) {
    int printmode_given[] = {args_info->print_given, args_info->filter_prefix_given,  -1};
    const char *printmode_desc[] = {"--print", "--filter-prefix",  0};
    int rlocmode_given[] = {args_info->interface_given,  -1};
    const char *rlocmode_desc[] = {"--interface",  0};
    error += check_modes(printmode_given, printmode_desc, rlocmode_given, rlocmode_desc);
  }
  
  if (check_required)
    {
      error += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
